# Copyright 2017 Yahoo Holdings. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
sudo: required

services:
   - docker

cache:
  timeout: 900
  directories:
  - $HOME/.m2
  - $HOME/.ccache

branches:
  only:
  - 7

before_cache:
  - sudo rm -rf $HOME/.m2/repository/com/yahoo/vespa
  - sudo rm -rf $HOME/.m2/repository/repository.xml
  - du --summarize --human-readable $HOME/.m2/repository
  - du --summarize --human-readable $HOME/.ccache

install: true

language: minimal

script: ./travis/travis.sh
